# Generated by Django 3.2.8 on 2023-08-02 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20230412_0833'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('image_url', models.URLField()),
                ('gender', models.CharField(max_length=10)),
                ('shirt_size', models.CharField(max_length=10)),
                ('pants_size', models.CharField(max_length=10)),
            ],
        ),
    ]
