# Generated by Django 3.2.8 on 2024-02-23 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='VolunteerAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VA_name', models.CharField(max_length=32, verbose_name='志愿活动名称')),
                ('VA_content', models.CharField(max_length=50, verbose_name='活动简介')),
            ],
        ),
        migrations.CreateModel(
            name='StuVolunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StuName', models.CharField(max_length=10, verbose_name='志愿者姓名')),
                ('StuId', models.CharField(max_length=8, verbose_name='志愿者学号')),
                ('NumId', models.CharField(max_length=18, verbose_name='志愿者身份证号')),
                ('StuAge', models.IntegerField(verbose_name='志愿者年龄')),
                ('StuAdress1', models.CharField(max_length=50, verbose_name='志愿者户籍地')),
                ('StuAdress2', models.CharField(max_length=50, verbose_name='志愿者现住址')),
                ('StuShirt', models.CharField(max_length=4, verbose_name='志愿者上衣尺寸')),
                ('StuTrousers', models.CharField(max_length=4, verbose_name='志愿者裤子尺寸')),
                ('StuGender', models.CharField(max_length=2, verbose_name='志愿者性别')),
                ('Action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.volunteeraction')),
            ],
        ),
    ]
