# Generated by Django 3.2.8 on 2024-02-23 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_stuvolunteer_volunteeraction'),
    ]

    operations = [
        migrations.AddField(
            model_name='stuvolunteer',
            name='StuCollege',
            field=models.CharField(default='-w-', max_length=20, verbose_name='志愿者学院'),
        ),
    ]
