# Generated by Django 3.2.8 on 2024-02-23 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_stuvolunteer_stucollege'),
    ]

    operations = [
        migrations.AddField(
            model_name='stuvolunteer',
            name='is_submit',
            field=models.BooleanField(default=False),
        ),
    ]
